### ISSUE TITLE
Band List similar problem to first early release of time tracking app

### ISSUE THREAD

**Issue by AGPVEN** [bandapps/bandapps.github.io#2]
Installed the tile in my band as prompted by app. Then after awhile, I open app and it says I don't have enough tiles.

**Comment by J-L** [comment]
100%! I knew this would happen, I've just been holding off pushing an update until I add more changes.

Ill push an update to the review queue tonight!

**Comment by AGPVEN** [comment]
Cool!

Hey one question that probably pertains to both List and Tracker:

Q: With Tracker, you start tracking something. After awhile, you do other
stuff. Time goes by. You use your iPhone for other things.

Eventually, I go to my band to stop tracking and switch to something else.
But the Tracker app is no longer connected and doesn't respond to the taps
I'm doing on the phone. I tested the follow to see what reestablishes
connection:

1) Close Track app and reopening: Doesn't work.
2) Perform sync with main Microsoft Band app...that generally WORKS. When I
go back to tap on Band tile, it now responds.

It's not so much having to do this that is problem, but rather it's:

1) Knowing definitively that this is a procedure that I must follow when X
period time goes by.
2) Perhaps, you figure out an automatic page/ping that maintains the
connection btwn Tracker app and Band.
3) Or is there something I can to preempt this from happening at all.
Example: Every time I do tap- or -out of a tracker on my band, I should
sync my main Microsoft Band app.

**Comment by J-L** [comment]
To be honest, the inability to run things definitely from the band is a real issue from an app designing perspective. 

I've tried to minimize the impact by putting in those vibrations to let you know that the action was accepted or not, but i haven't found a bullet proof way of getting them through.  It seems sometimes the second button press is captured, sometimes reopening the app will work... I don't really know the state of the underlying connection as it is obscured at the SDK level.

List applications work well enough with this model- typical use case involves using looking at the list on the phone somewhat near the time you consume it.  The time tracker sometimes falters if you don't touch it for hours.  Part of this is caused by iOS killing the app - if you see the 'Connecting to band..' page- that implies the app was killed by the phone. (I have no was of overriding the OS in this case, naturally)  Part of this might be states i haven't seen.

**Comment by AGPVEN** [comment]
Well...I'm looking forward to the list program then because I agree with
your point that it's less depending on real time synch than is the Timer
Tracker.

As for he time tracker, I wonder if there is kind of reliable way to
reconnect.

**Comment by J-L** [comment]
I'll ry and get in touch with the MS team and see if they have any tips.

**Comment by J-L** [comment]
1.2 has been released!

Also, here is the stack overflow on mitigating strategies for handling connection drops-  (nothing yet)

http://stackoverflow.com/questions/35161295/ios-retaining-connectivity-with-band
