### ISSUE TITLE
User Education or Bug? Background App Refresh

### ISSUE THREAD

**Issue by eximiusvir** [bandapps/bandapps.github.io#20]
How frequently does Background App Refresh pull data from Microsoft Health / Microsoft servers? What I feel I'm noticing is I woke this morning at 6:45 am and went about my chores. About 15 minutes later, I opened Apple Health to review my sleep and steps, but noticed while my previous night's sleep had been logged in Microsoft Health, it did not exist in Apple Health. 

I then opened Band Health Bridge and immediately upon opening it started its synchronization and stated it was synced up. I switched back to Apple Health and my nights sleep had been logged. 

As I've been going through my morning, I opened Apple Health and noticed my Steps were not being logged, with the last time reported being the sync I had done in the morning. I then opened Band Health Bridge, pressed Start Sync and the latest data updated and my steps were updated to reflect what I see on my band and in Microsoft Health. 

I've confirmed I have Background app Refresh enabled and I've ordered the priority in Apple Health to be Band Health Bridge above all others for those metrics it has "Write data" enabled. 

Thoughts? Is this a user education issue? Is there a way to increase the frequency of data sync'ing or was this a scenario where it would normally be expected that my data should be close to accurate within X minutes or so?

Thanks!

**Comment by eximiusvir** [comment]
Another thing I'm noticing is an oddity in the "Synced up to {Date}" label. 

The current date/time is 2016-03-06T09:03:00 (PST: Seattle). When I open the app, the app displays:

"Synced up to March 07, 2016 08:00:00 AM"

Given the actual current time, it's stating the date is ahead by one day (and despite pressing Start Sync, it remains on the date/time displayed). 

It's now 9:06 AM and I pressed Start Sync prior to submitting this issue and the label has updated to the hour 09:00 AM; however, still remains one day ahead. 

Thanks!

**Comment by bandapps** [comment]
Hey eximius,

The truth is I haven't figured out how to get backgroundSync firing.  I set it up, but for an unknown reason its not working.  I'll have another go at fixing it soon, I just have a couple other revisions I want to fix up for the other apps I have. As for when it would fire- Apple specs say the developer doesn't get to choose, we just get to say how much to prioritize it- iOS would decide how often it gets called.

As for the dates being a bit odd, that because the requester adds a date.  I understand it is a bit confusing, I'll change that it a future fix.

Best regards,

John
